services:
  web:
    build: .
    ports:
      - "0.0.0.0:5000:5000"
      - "0.0.0.0:8501:8501"
    volumes:
      - ./uploads:/app/uploads
    environment:
      - FLASK_ENV=development
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
